### ISSUE TITLE
TESearchSelectInput - Single - Documentation

### ISSUE THREAD

**Issue by mark-hoffmann** [SCasarotto/react-tec#12]
The documentation example is missing a `value` prop such that copying and pasting the example code does not work out of the box.

**Comment by SCasarotto** [comment]
Good catch. You can see in the code I do have it but not in the example code. https://github.com/SCasarotto/react-tec/blob/master/example/src/pages/Components/Form/TESearchSelectInputSection.js

I am thinking about migrating all of my examples to codesandbox. This would never happen in that case and you could play with it.

**Comment by SCasarotto** [comment]
You will find this fixed now on. See: https://www.react-tec.com/components/form/TESearchSelectInput
