### ISSUE TITLE
TEPrivateRoute dynamic isAuthenticated lookup

### ISSUE THREAD

**Issue by mark-hoffmann** [SCasarotto/react-tec#13]
It might be nice to add additional functionality such that you can do something like the following where based on the url extension of `:uid` you are able to use that variable in a function that you define and pass in to the isAuthenticated prop.

```
<TEPrivateRoute
	path='/site/data/:uid'
	component={Component}
	isAuthenticated={firebase.auth().currentUser && someCustomAuthenticationLookup(uid)}
	hasPermissions={user}
/>
```

**Comment by SCasarotto** [comment]
Added in 0.1.8. See updated docs
